<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>APS 240: Data Analysis and Statistics with R</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Course book for Data Analysis and Statistics with R (APS 240) in the Department of Animal and Plant Sciences, University of Sheffield">
  <meta name="generator" content="bookdown 0.1.5 and GitBook 2.6.7">

  <meta property="og:title" content="APS 240: Data Analysis and Statistics with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course book for Data Analysis and Statistics with R (APS 240) in the Department of Animal and Plant Sciences, University of Sheffield" />
  <meta name="github-repo" content="dzchilds/stats-for-bio" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="APS 240: Data Analysis and Statistics with R" />
  
  <meta name="twitter:description" content="Course book for Data Analysis and Statistics with R (APS 240) in the Department of Animal and Plant Sciences, University of Sheffield" />
  

<meta name="author" content="Dylan Z. Childs">

<meta name="date" content="2016-11-22">

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="two-sample-t-test.html">
<link rel="next" href="one-tailed-vs-two-tailed-tests.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<style type="text/css">

.warning-box {
  border: 3px solid #e60000;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

.advanced-box {
  border: 3px solid #268bd2;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

.do-something {
  border: 3px solid #803e00;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

</style>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">APS 240</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Course information and overview</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#why-data-analysis"><i class="fa fa-check"></i><b>1.1</b> Why do a data analysis course?</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#overview"><i class="fa fa-check"></i><b>1.2</b> Course overview</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#aims"><i class="fa fa-check"></i><b>1.2.1</b> Aims</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#objectives"><i class="fa fa-check"></i><b>1.2.2</b> Objectives</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#assumed-background"><i class="fa fa-check"></i><b>1.2.3</b> Assumed background</a></li>
<li class="chapter" data-level="1.2.4" data-path="index.html"><a href="index.html#methods"><i class="fa fa-check"></i><b>1.2.4</b> Methods</a></li>
<li class="chapter" data-level="1.2.5" data-path="index.html"><a href="index.html#non-assessed-material"><i class="fa fa-check"></i><b>1.2.5</b> Non-assessed material</a></li>
<li class="chapter" data-level="1.2.6" data-path="index.html"><a href="index.html#what-is-required-of-you"><i class="fa fa-check"></i><b>1.2.6</b> What is required of you?</a></li>
<li class="chapter" data-level="1.2.7" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>1.2.7</b> Assessment</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#how-to-use-the-teaching-material"><i class="fa fa-check"></i><b>1.3</b> How to use the teaching material</a><ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#printed-material"><i class="fa fa-check"></i><b>1.3.1</b> The online course book</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#printed-material"><i class="fa fa-check"></i><b>1.3.2</b> Printed material</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#how-to-make-best-use-of-it"><i class="fa fa-check"></i><b>1.3.3</b> How to make best use of the teaching material</a></li>
<li class="chapter" data-level="1.3.4" data-path="index.html"><a href="index.html#conventions"><i class="fa fa-check"></i><b>1.3.4</b> Conventions used in the course material</a></li>
<li class="chapter" data-level="1.3.5" data-path="index.html"><a href="index.html#feedback"><i class="fa fa-check"></i><b>1.3.5</b> Feedback</a></li>
<li class="chapter" data-level="1.3.6" data-path="index.html"><a href="index.html#help"><i class="fa fa-check"></i><b>1.3.6</b> Help sessions</a></li>
<li class="chapter" data-level="1.3.7" data-path="index.html"><a href="index.html#overall"><i class="fa fa-check"></i><b>1.3.7</b> Overall…</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#health-and-safety"><i class="fa fa-check"></i><b>1.4</b> Health and safety using display screen equipment</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html"><i class="fa fa-check"></i><b>2</b> Expected learning outcomes</a><ul>
<li class="chapter" data-level="2.1" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html#statistical-concepts-i"><i class="fa fa-check"></i><b>2.1</b> Statistical Concepts (I)</a></li>
<li class="chapter" data-level="2.2" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html#statistical-concepts-ii"><i class="fa fa-check"></i><b>2.2</b> Statistical Concepts (II)</a></li>
<li class="chapter" data-level="2.3" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html#simple-parametric-statistics-t-tests"><i class="fa fa-check"></i><b>2.3</b> Simple parametric statistics (<em>t</em>-tests)</a></li>
<li class="chapter" data-level="2.4" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html#categorical-data-chi-square-tests"><i class="fa fa-check"></i><b>2.4</b> Categorical Data (chi-square tests)</a></li>
<li class="chapter" data-level="2.5" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html#associations-and-relationships-regression"><i class="fa fa-check"></i><b>2.5</b> Associations and Relationships (regression)</a></li>
<li class="chapter" data-level="2.6" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html#associations-and-relationships-correlation"><i class="fa fa-check"></i><b>2.6</b> Associations and Relationships (correlation)</a></li>
<li class="chapter" data-level="2.7" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html#experimental-design-and-anova-i"><i class="fa fa-check"></i><b>2.7</b> Experimental Design and ANOVA (I)</a></li>
<li class="chapter" data-level="2.8" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html#experimental-design-and-anova-ii"><i class="fa fa-check"></i><b>2.8</b> Experimental Design and ANOVA (II)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html"><i class="fa fa-check"></i><b>3</b> Programming prerequisites</a><ul>
<li class="chapter" data-level="3.1" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#starting-an-r-session-in-rstudio"><i class="fa fa-check"></i><b>3.1</b> Starting an R session in RStudio</a></li>
<li class="chapter" data-level="3.2" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#using-packages"><i class="fa fa-check"></i><b>3.2</b> Using packages</a></li>
<li class="chapter" data-level="3.3" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#reading-data-into-r"><i class="fa fa-check"></i><b>3.3</b> Reading data into R</a></li>
<li class="chapter" data-level="3.4" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#data-frames"><i class="fa fa-check"></i><b>3.4</b> Data frames</a></li>
<li class="chapter" data-level="3.5" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#package-functions"><i class="fa fa-check"></i><b>3.5</b> Package functions</a></li>
</ul></li>
<li class="part"><span><b>Statistical Concepts (I)</b></span></li>
<li class="chapter" data-level="4" data-path="the-scientific-process.html"><a href="the-scientific-process.html"><i class="fa fa-check"></i><b>4</b> The scientific process</a><ul>
<li class="chapter" data-level="4.1" data-path="the-scientific-process.html"><a href="the-scientific-process.html#stages-scientific-process"><i class="fa fa-check"></i><b>4.1</b> Stages in the scientific process</a><ul>
<li class="chapter" data-level="4.1.1" data-path="the-scientific-process.html"><a href="the-scientific-process.html#stages-observations"><i class="fa fa-check"></i><b>4.1.1</b> Observations</a></li>
<li class="chapter" data-level="4.1.2" data-path="the-scientific-process.html"><a href="the-scientific-process.html#stages-questions"><i class="fa fa-check"></i><b>4.1.2</b> Questions</a></li>
<li class="chapter" data-level="4.1.3" data-path="the-scientific-process.html"><a href="the-scientific-process.html#stages-hypotheses"><i class="fa fa-check"></i><b>4.1.3</b> Hypotheses</a></li>
<li class="chapter" data-level="4.1.4" data-path="the-scientific-process.html"><a href="the-scientific-process.html#stages-predictions"><i class="fa fa-check"></i><b>4.1.4</b> Predictions</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="the-scientific-process.html"><a href="the-scientific-process.html#hypothesis-testing"><i class="fa fa-check"></i><b>4.2</b> Hypothesis testing</a></li>
<li class="chapter" data-level="4.3" data-path="the-scientific-process.html"><a href="the-scientific-process.html#are-we-sure"><i class="fa fa-check"></i><b>4.3</b> Don’t we ever know anything for sure?</a></li>
<li class="chapter" data-level="4.4" data-path="the-scientific-process.html"><a href="the-scientific-process.html#further-reading"><i class="fa fa-check"></i><b>4.4</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-and-variables.html"><a href="data-and-variables.html"><i class="fa fa-check"></i><b>5</b> Data and variables</a><ul>
<li class="chapter" data-level="5.1" data-path="data-and-variables.html"><a href="data-and-variables.html#observations-on-material-and-obvious-things"><i class="fa fa-check"></i><b>5.1</b> “Observations on material and obvious things”</a></li>
<li class="chapter" data-level="5.2" data-path="data-and-variables.html"><a href="data-and-variables.html#var-types"><i class="fa fa-check"></i><b>5.2</b> Revision: Types of variable</a><ul>
<li class="chapter" data-level="5.2.1" data-path="data-and-variables.html"><a href="data-and-variables.html#nominal-categorical-variables"><i class="fa fa-check"></i><b>5.2.1</b> Nominal (categorical) variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-and-variables.html"><a href="data-and-variables.html#ordinal-categorical-data"><i class="fa fa-check"></i><b>5.2.2</b> Ordinal (categorical) data</a></li>
<li class="chapter" data-level="5.2.3" data-path="data-and-variables.html"><a href="data-and-variables.html#interval-scale-numeric-variables"><i class="fa fa-check"></i><b>5.2.3</b> Interval scale (numeric) variables</a></li>
<li class="chapter" data-level="5.2.4" data-path="data-and-variables.html"><a href="data-and-variables.html#ratio-scale-numeric-variables"><i class="fa fa-check"></i><b>5.2.4</b> Ratio scale (numeric) variables</a></li>
<li class="chapter" data-level="5.2.5" data-path="data-and-variables.html"><a href="data-and-variables.html#which-is-best"><i class="fa fa-check"></i><b>5.2.5</b> Which is best?</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-and-variables.html"><a href="data-and-variables.html#accuracy-precision"><i class="fa fa-check"></i><b>5.3</b> Accuracy and precision</a><ul>
<li class="chapter" data-level="5.3.1" data-path="data-and-variables.html"><a href="data-and-variables.html#what-do-they-mean"><i class="fa fa-check"></i><b>5.3.1</b> What do they mean?</a></li>
<li class="chapter" data-level="5.3.2" data-path="data-and-variables.html"><a href="data-and-variables.html#implied-precision---significant-figures"><i class="fa fa-check"></i><b>5.3.2</b> Implied precision - significant figures</a></li>
<li class="chapter" data-level="5.3.3" data-path="data-and-variables.html"><a href="data-and-variables.html#how-precise-should-measurements-be"><i class="fa fa-check"></i><b>5.3.3</b> How precise should measurements be?</a></li>
<li class="chapter" data-level="5.3.4" data-path="data-and-variables.html"><a href="data-and-variables.html#error-bias-and-prejudice"><i class="fa fa-check"></i><b>5.3.4</b> Error, bias and prejudice</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="learning-from-data.html"><a href="learning-from-data.html"><i class="fa fa-check"></i><b>6</b> Learning from data</a><ul>
<li class="chapter" data-level="6.1" data-path="learning-from-data.html"><a href="learning-from-data.html#populations"><i class="fa fa-check"></i><b>6.1</b> Populations</a></li>
<li class="chapter" data-level="6.2" data-path="learning-from-data.html"><a href="learning-from-data.html#learning-about-populations"><i class="fa fa-check"></i><b>6.2</b> Learning about populations</a></li>
<li class="chapter" data-level="6.3" data-path="learning-from-data.html"><a href="learning-from-data.html#morph-example"><i class="fa fa-check"></i><b>6.3</b> A simple example</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sampling-error.html"><a href="sampling-error.html"><i class="fa fa-check"></i><b>7</b> Sampling error</a><ul>
<li class="chapter" data-level="7.1" data-path="sampling-error.html"><a href="sampling-error.html#sampling-error-1"><i class="fa fa-check"></i><b>7.1</b> Sampling error</a></li>
<li class="chapter" data-level="7.2" data-path="sampling-error.html"><a href="sampling-error.html#sampling-distributions"><i class="fa fa-check"></i><b>7.2</b> Sampling distributions</a></li>
<li class="chapter" data-level="7.3" data-path="sampling-error.html"><a href="sampling-error.html#the-effect-of-sample-size"><i class="fa fa-check"></i><b>7.3</b> The effect of sample size</a></li>
<li class="chapter" data-level="7.4" data-path="sampling-error.html"><a href="sampling-error.html#the-standard-error"><i class="fa fa-check"></i><b>7.4</b> The standard error</a></li>
<li class="chapter" data-level="7.5" data-path="sampling-error.html"><a href="sampling-error.html#what-is-the-point-of-all-this"><i class="fa fa-check"></i><b>7.5</b> What is the point of all this!?</a></li>
</ul></li>
<li class="part"><span><b>Statistical Concepts (II)</b></span></li>
<li class="chapter" data-level="8" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html"><i class="fa fa-check"></i><b>8</b> Statistical significance and <em>p</em>-values</a><ul>
<li class="chapter" data-level="8.1" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#bootstrap"><i class="fa fa-check"></i><b>8.1</b> Estimating a sampling distribution</a><ul>
<li class="chapter" data-level="8.1.1" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#bootstrap-overview"><i class="fa fa-check"></i><b>8.1.1</b> Overview of bootstrapping</a></li>
<li class="chapter" data-level="8.1.2" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#doing-it-for-real"><i class="fa fa-check"></i><b>8.1.2</b> Doing it for real</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#statistical-significance"><i class="fa fa-check"></i><b>8.2</b> Statistical significance</a></li>
<li class="chapter" data-level="8.3" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#concluding-remarks"><i class="fa fa-check"></i><b>8.3</b> Concluding remarks</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="comparing-populations.html"><a href="comparing-populations.html"><i class="fa fa-check"></i><b>9</b> Comparing populations</a><ul>
<li class="chapter" data-level="9.1" data-path="comparing-populations.html"><a href="comparing-populations.html#making-comparisons"><i class="fa fa-check"></i><b>9.1</b> Making comparisons</a></li>
<li class="chapter" data-level="9.2" data-path="comparing-populations.html"><a href="comparing-populations.html#morph-weights-eg"><i class="fa fa-check"></i><b>9.2</b> A new example</a></li>
<li class="chapter" data-level="9.3" data-path="comparing-populations.html"><a href="comparing-populations.html#evaluating-differences-between-population-means"><i class="fa fa-check"></i><b>9.3</b> Evaluating differences between population means</a></li>
<li class="chapter" data-level="9.4" data-path="comparing-populations.html"><a href="comparing-populations.html#a-permutation-test"><i class="fa fa-check"></i><b>9.4</b> A permutation test</a></li>
<li class="chapter" data-level="9.5" data-path="comparing-populations.html"><a href="comparing-populations.html#what-have-we-learned"><i class="fa fa-check"></i><b>9.5</b> What have we learned?</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="hypotheses-and-p-values.html"><a href="hypotheses-and-p-values.html"><i class="fa fa-check"></i><b>10</b> Hypotheses and <em>p</em>-values</a><ul>
<li class="chapter" data-level="10.1" data-path="hypotheses-and-p-values.html"><a href="hypotheses-and-p-values.html#a-few-words-about-the-null-hypothesis"><i class="fa fa-check"></i><b>10.1</b> A few words about the null hypothesis</a><ul>
<li class="chapter" data-level="10.1.1" data-path="hypotheses-and-p-values.html"><a href="hypotheses-and-p-values.html#hypotheses-and-null-hypotheses"><i class="fa fa-check"></i><b>10.1.1</b> Hypotheses and null hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="hypotheses-and-p-values.html"><a href="hypotheses-and-p-values.html#interpreting-and-reporting-p-values"><i class="fa fa-check"></i><b>10.2</b> Interpreting and reporting <em>p</em>-values</a><ul>
<li class="chapter" data-level="10.2.1" data-path="hypotheses-and-p-values.html"><a href="hypotheses-and-p-values.html#what-if-p-is-close-to-0.05"><i class="fa fa-check"></i><b>10.2.1</b> What if <em>p</em> is close to 0.05?</a></li>
<li class="chapter" data-level="10.2.2" data-path="hypotheses-and-p-values.html"><a href="hypotheses-and-p-values.html#presenting-p-values"><i class="fa fa-check"></i><b>10.2.2</b> Presenting <em>p</em>-values</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="hypotheses-and-p-values.html"><a href="hypotheses-and-p-values.html#biological-vs.statistical-significance"><i class="fa fa-check"></i><b>10.3</b> Biological vs. statistical significance</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="parametric-statistics.html"><a href="parametric-statistics.html"><i class="fa fa-check"></i><b>11</b> Parametric statistics</a><ul>
<li class="chapter" data-level="11.1" data-path="parametric-statistics.html"><a href="parametric-statistics.html#introduction"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="parametric-statistics.html"><a href="parametric-statistics.html#math-models"><i class="fa fa-check"></i><b>11.2</b> Mathematical models</a></li>
<li class="chapter" data-level="11.3" data-path="parametric-statistics.html"><a href="parametric-statistics.html#parametric-stats"><i class="fa fa-check"></i><b>11.3</b> The normal distribution</a><ul>
<li class="chapter" data-level="11.3.1" data-path="parametric-statistics.html"><a href="parametric-statistics.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>11.3.1</b> Standard error of the mean</a></li>
<li class="chapter" data-level="11.3.2" data-path="parametric-statistics.html"><a href="parametric-statistics.html#the-t-distribution"><i class="fa fa-check"></i><b>11.3.2</b> The <em>t</em> distribution</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Simple Parametric Statistics</b></span></li>
<li class="chapter" data-level="12" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html"><i class="fa fa-check"></i><b>12</b> One sample <em>t</em>-tests</a><ul>
<li class="chapter" data-level="12.1" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html#when-do-we-use-one-sample-t-test"><i class="fa fa-check"></i><b>12.1</b> When do we use one-sample <em>t</em>-test?</a></li>
<li class="chapter" data-level="12.2" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html#how-does-the-one-sample-t-test-work"><i class="fa fa-check"></i><b>12.2</b> How does the one-sample <em>t</em>-test work?</a><ul>
<li class="chapter" data-level="12.2.1" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html#assumptions-of-the-one-sample-t-test"><i class="fa fa-check"></i><b>12.2.1</b> Assumptions of the one-sample <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html#carrying-out-a-one-sample-t-test-in-r"><i class="fa fa-check"></i><b>12.3</b> Carrying out a one-sample <em>t</em>-test in R</a><ul>
<li class="chapter" data-level="12.3.1" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html#visualising-the-data-and-checking-the-assumptions"><i class="fa fa-check"></i><b>12.3.1</b> Visualising the data and checking the assumptions</a></li>
<li class="chapter" data-level="12.3.2" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html#carrying-out-the-test"><i class="fa fa-check"></i><b>12.3.2</b> Carrying out the test</a></li>
<li class="chapter" data-level="12.3.3" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html#summarising-the-result"><i class="fa fa-check"></i><b>12.3.3</b> Summarising the result</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="two-sample-t-test.html"><a href="two-sample-t-test.html"><i class="fa fa-check"></i><b>13</b> Two-sample <em>t</em>-test</a><ul>
<li class="chapter" data-level="13.1" data-path="two-sample-t-test.html"><a href="two-sample-t-test.html#when-do-we-use-a-two-sample-t-test"><i class="fa fa-check"></i><b>13.1</b> When do we use a two-sample <em>t</em>-test?</a></li>
<li class="chapter" data-level="13.2" data-path="two-sample-t-test.html"><a href="two-sample-t-test.html#how-does-the-two-sample-t-test-work"><i class="fa fa-check"></i><b>13.2</b> How does the two-sample <em>t</em>-test work?</a><ul>
<li class="chapter" data-level="13.2.1" data-path="two-sample-t-test.html"><a href="two-sample-t-test.html#assumptions-of-the-two-sample-t-test"><i class="fa fa-check"></i><b>13.2.1</b> Assumptions of the two-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="13.2.2" data-path="two-sample-t-test.html"><a href="two-sample-t-test.html#what-about-the-equal-variance-assumption"><i class="fa fa-check"></i><b>13.2.2</b> What about the <em>equal variance</em> assumption?</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="two-sample-t-test.html"><a href="two-sample-t-test.html#carrying-out-a-two-sample-t-test-in-r"><i class="fa fa-check"></i><b>13.3</b> Carrying out a two-sample <em>t</em>-test in R</a><ul>
<li class="chapter" data-level="13.3.1" data-path="two-sample-t-test.html"><a href="two-sample-t-test.html#visualising-the-data-and-checking-the-assumptions-1"><i class="fa fa-check"></i><b>13.3.1</b> Visualising the data and checking the assumptions</a></li>
<li class="chapter" data-level="13.3.2" data-path="two-sample-t-test.html"><a href="two-sample-t-test.html#carrying-out-the-test-1"><i class="fa fa-check"></i><b>13.3.2</b> Carrying out the test</a></li>
<li class="chapter" data-level="13.3.3" data-path="two-sample-t-test.html"><a href="two-sample-t-test.html#summarising-the-result-1"><i class="fa fa-check"></i><b>13.3.3</b> Summarising the result</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="paired-sample-t-tests.html"><a href="paired-sample-t-tests.html"><i class="fa fa-check"></i><b>14</b> Paired-sample <em>t</em>-tests</a><ul>
<li class="chapter" data-level="14.1" data-path="paired-sample-t-tests.html"><a href="paired-sample-t-tests.html#when-do-we-use-a-paired-sample-t-test"><i class="fa fa-check"></i><b>14.1</b> When do we use a paired-sample <em>t</em>-test?</a></li>
<li class="chapter" data-level="14.2" data-path="paired-sample-t-tests.html"><a href="paired-sample-t-tests.html#why-do-we-use-a-paired-sample-design"><i class="fa fa-check"></i><b>14.2</b> Why do we use a paired-sample design?</a></li>
<li class="chapter" data-level="14.3" data-path="paired-sample-t-tests.html"><a href="paired-sample-t-tests.html#how-do-you-carry-out-a-t-test-on-paired-samples"><i class="fa fa-check"></i><b>14.3</b> How do you carry out a <em>t</em>-test on paired-samples?</a><ul>
<li class="chapter" data-level="14.3.1" data-path="paired-sample-t-tests.html"><a href="paired-sample-t-tests.html#assumptions-of-the-one-sample-t-test-1"><i class="fa fa-check"></i><b>14.3.1</b> Assumptions of the one-sample <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="paired-sample-t-tests.html"><a href="paired-sample-t-tests.html#carrying-out-a-paired-sample-t-test-in-r"><i class="fa fa-check"></i><b>14.4</b> Carrying out a paired-sample <em>t</em>-test in R</a><ul>
<li class="chapter" data-level="14.4.1" data-path="paired-sample-t-tests.html"><a href="paired-sample-t-tests.html#using-the-paired-true-argument"><i class="fa fa-check"></i><b>14.4.1</b> Using the <code>paired = TRUE</code> argument</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="one-tailed-vs-two-tailed-tests.html"><a href="one-tailed-vs-two-tailed-tests.html"><i class="fa fa-check"></i><b>15</b> One-tailed vs. two-tailed tests</a><ul>
<li class="chapter" data-level="15.1" data-path="one-tailed-vs-two-tailed-tests.html"><a href="one-tailed-vs-two-tailed-tests.html#introduction-1"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="one-tailed-vs-two-tailed-tests.html"><a href="one-tailed-vs-two-tailed-tests.html#an-example-of-a-one-tailed-hypothesis"><i class="fa fa-check"></i><b>15.2</b> An example of a one-tailed hypothesis</a></li>
<li class="chapter" data-level="15.3" data-path="one-tailed-vs-two-tailed-tests.html"><a href="one-tailed-vs-two-tailed-tests.html#so-how-do-we-perform-a-one-tailed-t-test"><i class="fa fa-check"></i><b>15.3</b> So how do we perform a one-tailed <em>t</em>-test?</a><ul>
<li class="chapter" data-level="15.3.1" data-path="one-tailed-vs-two-tailed-tests.html"><a href="one-tailed-vs-two-tailed-tests.html#carrying-out-one-tailed-t-tests-in-r"><i class="fa fa-check"></i><b>15.3.1</b> Carrying out one-tailed <em>t</em>-tests in R</a></li>
<li class="chapter" data-level="15.3.2" data-path="one-tailed-vs-two-tailed-tests.html"><a href="one-tailed-vs-two-tailed-tests.html#when-to-use-and-not-to-use-one-tailed-t-tests"><i class="fa fa-check"></i><b>15.3.2</b> When to use, and not to use, one-tailed <em>t</em>-tests</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Categorical Data</b></span></li>
<li class="chapter" data-level="16" data-path="working-with-frequencies.html"><a href="working-with-frequencies.html"><i class="fa fa-check"></i><b>16</b> Working with frequencies</a><ul>
<li class="chapter" data-level="16.1" data-path="working-with-frequencies.html"><a href="working-with-frequencies.html#introduction-2"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="working-with-frequencies.html"><a href="working-with-frequencies.html#a-new-kind-of-distribution"><i class="fa fa-check"></i><b>16.2</b> A new kind of distribution</a></li>
<li class="chapter" data-level="16.3" data-path="working-with-frequencies.html"><a href="working-with-frequencies.html#types-of-test"><i class="fa fa-check"></i><b>16.3</b> Types of test</a><ul>
<li class="chapter" data-level="16.3.1" data-path="working-with-frequencies.html"><a href="working-with-frequencies.html#chi2-goodness-of-fit-test"><i class="fa fa-check"></i><b>16.3.1</b> <span class="math inline">\(\chi^{2}\)</span> goodness of fit test</a></li>
<li class="chapter" data-level="16.3.2" data-path="working-with-frequencies.html"><a href="working-with-frequencies.html#chi2-contingency-table-test"><i class="fa fa-check"></i><b>16.3.2</b> <span class="math inline">\(\chi^{2}\)</span> contingency table test</a></li>
<li class="chapter" data-level="16.3.3" data-path="working-with-frequencies.html"><a href="working-with-frequencies.html#the-assumptions-and-requirements-of-chi2-tests"><i class="fa fa-check"></i><b>16.3.3</b> The assumptions and requirements of <span class="math inline">\(\chi^{2}\)</span> tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="goodness-of-fit-tests.html"><a href="goodness-of-fit-tests.html"><i class="fa fa-check"></i><b>17</b> Goodness of fit tests</a><ul>
<li class="chapter" data-level="17.1" data-path="goodness-of-fit-tests.html"><a href="goodness-of-fit-tests.html#when-do-we-use-a-chi-square-goodness-of-fit-test"><i class="fa fa-check"></i><b>17.1</b> When do we use a chi-square goodness of fit test?</a></li>
<li class="chapter" data-level="17.2" data-path="goodness-of-fit-tests.html"><a href="goodness-of-fit-tests.html#how-does-the-chi-square-goodness-of-fit-test-work"><i class="fa fa-check"></i><b>17.2</b> How does the chi-square goodness of fit test work?</a><ul>
<li class="chapter" data-level="17.2.1" data-path="goodness-of-fit-tests.html"><a href="goodness-of-fit-tests.html#assumptions-of-the-chi-square-goodness-of-fit-test"><i class="fa fa-check"></i><b>17.2.1</b> Assumptions of the chi-square goodness of fit test</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="goodness-of-fit-tests.html"><a href="goodness-of-fit-tests.html#carrying-out-a-chi-square-goodness-of-fit-test-in-r"><i class="fa fa-check"></i><b>17.3</b> Carrying out a chi-square goodness of fit test in R</a><ul>
<li class="chapter" data-level="17.3.1" data-path="goodness-of-fit-tests.html"><a href="goodness-of-fit-tests.html#summarising-the-result-2"><i class="fa fa-check"></i><b>17.3.1</b> Summarising the result</a></li>
<li class="chapter" data-level="17.3.2" data-path="goodness-of-fit-tests.html"><a href="goodness-of-fit-tests.html#a-bit-more-about-goodness-of-fit-tests-in-r"><i class="fa fa-check"></i><b>17.3.2</b> A bit more about goodness of fit tests in R</a></li>
<li class="chapter" data-level="17.3.3" data-path="goodness-of-fit-tests.html"><a href="goodness-of-fit-tests.html#doing-it-the-long-way"><i class="fa fa-check"></i><b>17.3.3</b> Doing it the long way…</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="goodness-of-fit-tests.html"><a href="goodness-of-fit-tests.html#determining-appropriate-expected-values"><i class="fa fa-check"></i><b>17.4</b> Determining appropriate expected values</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="contingency-tables.html"><a href="contingency-tables.html"><i class="fa fa-check"></i><b>18</b> Contingency tables</a><ul>
<li class="chapter" data-level="18.1" data-path="contingency-tables.html"><a href="contingency-tables.html#when-do-we-use-a-chi-square-contingency-table-test"><i class="fa fa-check"></i><b>18.1</b> When do we use a chi-square contingency table test?</a></li>
<li class="chapter" data-level="18.2" data-path="contingency-tables.html"><a href="contingency-tables.html#how-does-the-chi-square-contingency-table-test-work"><i class="fa fa-check"></i><b>18.2</b>  How does the chi-square contingency table test work?</a><ul>
<li class="chapter" data-level="18.2.1" data-path="contingency-tables.html"><a href="contingency-tables.html#assumptions-of-the-chi-square-contingency-table-test"><i class="fa fa-check"></i><b>18.2.1</b> Assumptions of the chi-square contingency table test</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="contingency-tables.html"><a href="contingency-tables.html#carrying-out-a-chi-square-contingency-table-test-in-r"><i class="fa fa-check"></i><b>18.3</b> Carrying out a chi-square contingency table test in R</a><ul>
<li class="chapter" data-level="18.3.1" data-path="contingency-tables.html"><a href="contingency-tables.html#step-1.-getting-the-data-into-the-correct-format"><i class="fa fa-check"></i><b>18.3.1</b> Step 1. Getting the data into the correct format</a></li>
<li class="chapter" data-level="18.3.2" data-path="contingency-tables.html"><a href="contingency-tables.html#step-2.-doing-the-test"><i class="fa fa-check"></i><b>18.3.2</b> Step 2. Doing the test</a></li>
<li class="chapter" data-level="18.3.3" data-path="contingency-tables.html"><a href="contingency-tables.html#summarising-the-result-3"><i class="fa fa-check"></i><b>18.3.3</b> Summarising the result</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="contingency-tables.html"><a href="contingency-tables.html#working-with-larger-tables"><i class="fa fa-check"></i><b>18.4</b> Working with larger tables</a></li>
</ul></li>
<li class="part"><span><b>Associations and Relationships</b></span></li>
<li class="chapter" data-level="19" data-path="relationships-and-regression.html"><a href="relationships-and-regression.html"><i class="fa fa-check"></i><b>19</b> Relationships and regression</a><ul>
<li class="chapter" data-level="19.1" data-path="relationships-and-regression.html"><a href="relationships-and-regression.html#introduction-3"><i class="fa fa-check"></i><b>19.1</b> Introduction</a></li>
<li class="chapter" data-level="19.2" data-path="relationships-and-regression.html"><a href="relationships-and-regression.html#what-does-linear-regression-do"><i class="fa fa-check"></i><b>19.2</b> What does linear regression do?</a></li>
<li class="chapter" data-level="19.3" data-path="relationships-and-regression.html"><a href="relationships-and-regression.html#how-does-simple-linear-regression-work"><i class="fa fa-check"></i><b>19.3</b> How does simple linear regression work?</a><ul>
<li class="chapter" data-level="19.3.1" data-path="relationships-and-regression.html"><a href="relationships-and-regression.html#finding-the-best-fit-line"><i class="fa fa-check"></i><b>19.3.1</b> Finding the best fit line</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="relationships-and-regression.html"><a href="relationships-and-regression.html#what-do-you-get-out-of-a-regression"><i class="fa fa-check"></i><b>19.4</b> What do you get out of a regression?</a><ul>
<li class="chapter" data-level="19.4.1" data-path="relationships-and-regression.html"><a href="relationships-and-regression.html#interpreting-a-regression"><i class="fa fa-check"></i><b>19.4.1</b> Interpreting a regression</a></li>
<li class="chapter" data-level="19.4.2" data-path="relationships-and-regression.html"><a href="relationships-and-regression.html#evaluating-hypotheses-inference"><i class="fa fa-check"></i><b>19.4.2</b> Evaluating hypotheses (‘inference’)</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="relationships-and-regression.html"><a href="relationships-and-regression.html#the-assumptions-of-regression"><i class="fa fa-check"></i><b>19.5</b> The assumptions of regression</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html"><i class="fa fa-check"></i><b>20</b> Simple regression in R</a><ul>
<li class="chapter" data-level="20.1" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#regression-in-R"><i class="fa fa-check"></i><b>20.1</b> Carrying out a simple linear regression in R</a></li>
<li class="chapter" data-level="20.2" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#first-steps"><i class="fa fa-check"></i><b>20.2</b> First steps</a><ul>
<li class="chapter" data-level="20.2.1" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#visualising-the-data"><i class="fa fa-check"></i><b>20.2.1</b> Visualising the data</a></li>
<li class="chapter" data-level="20.2.2" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#checking-the-assumptions"><i class="fa fa-check"></i><b>20.2.2</b> Checking the assumptions</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#model-fitting-and-significance-tests"><i class="fa fa-check"></i><b>20.3</b> Model fitting and significance tests</a><ul>
<li class="chapter" data-level="20.3.1" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#extracting-a-little-more-information"><i class="fa fa-check"></i><b>20.3.1</b> Extracting a little more information</a></li>
<li class="chapter" data-level="20.3.2" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#residual-analysis"><i class="fa fa-check"></i><b>20.3.2</b> Residual analysis</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#present-results"><i class="fa fa-check"></i><b>20.4</b> Presenting results</a><ul>
<li class="chapter" data-level="20.4.1" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#plotting-the-fitted-line-and-the-data"><i class="fa fa-check"></i><b>20.4.1</b> Plotting the fitted line and the data</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="simple-regression-in-r.html"><a href="simple-regression-in-r.html#causation"><i class="fa fa-check"></i><b>20.5</b> What about causation?</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html"><i class="fa fa-check"></i><b>21</b> Regression diagnostics</a><ul>
<li class="chapter" data-level="21.1" data-path="parametric-statistics.html"><a href="parametric-statistics.html#introduction"><i class="fa fa-check"></i><b>21.1</b> Introduction</a><ul>
<li class="chapter" data-level="21.1.1" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#understanding-data"><i class="fa fa-check"></i><b>21.1.1</b> Understanding data</a></li>
<li class="chapter" data-level="21.1.2" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#checking-assumptions"><i class="fa fa-check"></i><b>21.1.2</b> Checking assumptions</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#regres-diagnose"><i class="fa fa-check"></i><b>21.2</b> Diagnostics for simple linear regression</a><ul>
<li class="chapter" data-level="21.2.1" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#a-simple-linear-regression-example"><i class="fa fa-check"></i><b>21.2.1</b> A simple linear regression example</a></li>
<li class="chapter" data-level="21.2.2" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#simple-checks"><i class="fa fa-check"></i><b>21.2.2</b> Simple checks</a></li>
<li class="chapter" data-level="21.2.3" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#fitted-values"><i class="fa fa-check"></i><b>21.2.3</b> Fitted values</a></li>
<li class="chapter" data-level="21.2.4" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#checking-the-linearity-assumption"><i class="fa fa-check"></i><b>21.2.4</b> Checking the linearity assumption</a></li>
<li class="chapter" data-level="21.2.5" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#checking-the-normality-assumption"><i class="fa fa-check"></i><b>21.2.5</b> Checking the normality assumption</a></li>
<li class="chapter" data-level="21.2.6" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#checking-the-constant-variance-assumption"><i class="fa fa-check"></i><b>21.2.6</b> Checking the constant variance assumption</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#regression-diagnostics-the-easy-way"><i class="fa fa-check"></i><b>21.3</b> Regression diagnostics the easy way</a></li>
<li class="chapter" data-level="21.4" data-path="regression-diagnostics.html"><a href="regression-diagnostics.html#other-diagnose"><i class="fa fa-check"></i><b>21.4</b> Diagnostics for other kinds of models</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>22</b> Correlation</a><ul>
<li class="chapter" data-level="22.1" data-path="correlation.html"><a href="correlation.html#introduction-4"><i class="fa fa-check"></i><b>22.1</b> Introduction</a></li>
<li class="chapter" data-level="22.2" data-path="correlation.html"><a href="correlation.html#correlation-and-regression"><i class="fa fa-check"></i><b>22.2</b> Correlation and regression</a></li>
<li class="chapter" data-level="22.3" data-path="correlation.html"><a href="correlation.html#pearsons-product-moment-correlation-coefficient"><i class="fa fa-check"></i><b>22.3</b> Pearson’s product-moment correlation coefficient</a><ul>
<li class="chapter" data-level="22.3.1" data-path="correlation.html"><a href="correlation.html#pearsons-product-moment-correlation-coefficient-in-r"><i class="fa fa-check"></i><b>22.3.1</b> Pearson’s product-moment correlation coefficient in R</a></li>
<li class="chapter" data-level="22.3.2" data-path="correlation.html"><a href="correlation.html#reporting-the-result"><i class="fa fa-check"></i><b>22.3.2</b> Reporting the result</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="correlation.html"><a href="correlation.html#spearmans-rank-correlation"><i class="fa fa-check"></i><b>22.4</b> Spearman’s rank correlation</a><ul>
<li class="chapter" data-level="22.4.1" data-path="correlation.html"><a href="correlation.html#spearmans-rank-correlation-coefficient-in-r"><i class="fa fa-check"></i><b>22.4.1</b> Spearman’s rank correlation coefficient in R</a></li>
<li class="chapter" data-level="22.4.2" data-path="correlation.html"><a href="correlation.html#reporting-the-result-1"><i class="fa fa-check"></i><b>22.4.2</b> Reporting the result</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Experimental Design and ANOVA (I)</b></span></li>
<li class="chapter" data-level="23" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html"><i class="fa fa-check"></i><b>23</b> Principles of experimental design</a><ul>
<li class="chapter" data-level="23.1" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#introduction-5"><i class="fa fa-check"></i><b>23.1</b> Introduction</a></li>
<li class="chapter" data-level="23.2" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#jargon-busting"><i class="fa fa-check"></i><b>23.2</b> Jargon busting</a></li>
<li class="chapter" data-level="23.3" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#replication"><i class="fa fa-check"></i><b>23.3</b> Replication</a><ul>
<li class="chapter" data-level="23.3.1" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#independence"><i class="fa fa-check"></i><b>23.3.1</b> Independence and pseudoreplication</a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#controls"><i class="fa fa-check"></i><b>23.4</b> Controls</a></li>
<li class="chapter" data-level="23.5" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#confounded-and-noisy-experiments"><i class="fa fa-check"></i><b>23.5</b> Confounded and noisy experiments</a><ul>
<li class="chapter" data-level="23.5.1" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#confounding"><i class="fa fa-check"></i><b>23.5.1</b> Confounding</a></li>
<li class="chapter" data-level="23.5.2" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#noise"><i class="fa fa-check"></i><b>23.5.2</b> Noise</a></li>
</ul></li>
<li class="chapter" data-level="23.6" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#dealing-with-confounding-effects-and-noise"><i class="fa fa-check"></i><b>23.6</b> Dealing with confounding effects and noise</a><ul>
<li class="chapter" data-level="23.6.1" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#randomisation"><i class="fa fa-check"></i><b>23.6.1</b> Randomisation</a></li>
<li class="chapter" data-level="23.6.2" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#blocking"><i class="fa fa-check"></i><b>23.6.2</b> Blocking</a></li>
<li class="chapter" data-level="23.6.3" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#experimental-control"><i class="fa fa-check"></i><b>23.6.3</b> Experimental control</a></li>
<li class="chapter" data-level="23.6.4" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#additional-treatments-designing-in-unwanted-variation"><i class="fa fa-check"></i><b>23.6.4</b> Additional treatments: ‘designing in’ unwanted variation</a></li>
</ul></li>
<li class="chapter" data-level="23.7" data-path="principles-of-experimental-design.html"><a href="principles-of-experimental-design.html#ethics-and-practicality"><i class="fa fa-check"></i><b>23.7</b> Ethics and practicality</a></li>
<li class="chapter" data-level="23.8" data-path="the-scientific-process.html"><a href="the-scientific-process.html#further-reading"><i class="fa fa-check"></i><b>23.8</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html"><i class="fa fa-check"></i><b>24</b> Introduction to one-way ANOVA</a><ul>
<li class="chapter" data-level="24.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#intro"><i class="fa fa-check"></i><b>24.1</b> Introduction</a></li>
<li class="chapter" data-level="24.2" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#why-do-we-need-anova-models"><i class="fa fa-check"></i><b>24.2</b> Why do we need ANOVA models?</a></li>
<li class="chapter" data-level="24.3" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#how-does-anova-work"><i class="fa fa-check"></i><b>24.3</b> How does ANOVA work?</a><ul>
<li class="chapter" data-level="24.3.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#degrees-of-freedom"><i class="fa fa-check"></i><b>24.3.1</b> Degrees of freedom</a></li>
<li class="chapter" data-level="24.3.2" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#mean-squares-variance-ratios-and-f-tests"><i class="fa fa-check"></i><b>24.3.2</b> Mean squares, variance ratios, and F-tests</a></li>
<li class="chapter" data-level="24.3.3" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#assumptions-of-anova"><i class="fa fa-check"></i><b>24.3.3</b> Assumptions of ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="24.4" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#different-kinds-of-anova-model"><i class="fa fa-check"></i><b>24.4</b> Different kinds of ANOVA model</a></li>
<li class="chapter" data-level="24.5" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#questions"><i class="fa fa-check"></i><b>24.5</b> Some common questions about ANOVA</a><ul>
<li class="chapter" data-level="24.5.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#can-anova-only-be-applied-to-experimental-data"><i class="fa fa-check"></i><b>24.5.1</b> Can ANOVA only be applied to experimental data?</a></li>
<li class="chapter" data-level="24.5.2" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#do-we-need-equal-replication"><i class="fa fa-check"></i><b>24.5.2</b> Do we need equal replication?</a></li>
<li class="chapter" data-level="24.5.3" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#can-anova-be-done-with-only-two-treatments"><i class="fa fa-check"></i><b>24.5.3</b> Can ANOVA be done with only two treatments?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="25" data-path="one-way-anova-in-r.html"><a href="one-way-anova-in-r.html"><i class="fa fa-check"></i><b>25</b> One-way ANOVA in R</a><ul>
<li class="chapter" data-level="25.1" data-path="one-way-anova-in-r.html"><a href="one-way-anova-in-r.html#introduction-6"><i class="fa fa-check"></i><b>25.1</b> Introduction</a></li>
<li class="chapter" data-level="25.2" data-path="one-way-anova-in-r.html"><a href="one-way-anova-in-r.html#factors-in-r"><i class="fa fa-check"></i><b>25.2</b> Factors in R</a></li>
<li class="chapter" data-level="25.3" data-path="one-way-anova-in-r.html"><a href="one-way-anova-in-r.html#roughly-checking-the-assumptions"><i class="fa fa-check"></i><b>25.3</b> Roughly checking the assumptions</a></li>
<li class="chapter" data-level="25.4" data-path="one-way-anova-in-r.html"><a href="one-way-anova-in-r.html#fitting-the-anova-model"><i class="fa fa-check"></i><b>25.4</b> Fitting the ANOVA model</a></li>
<li class="chapter" data-level="25.5" data-path="one-way-anova-in-r.html"><a href="one-way-anova-in-r.html#diagnostics"><i class="fa fa-check"></i><b>25.5</b> Diagnostics</a><ul>
<li class="chapter" data-level="25.5.1" data-path="one-way-anova-in-r.html"><a href="one-way-anova-in-r.html#aside-formal-test-of-equality-of-variance"><i class="fa fa-check"></i><b>25.5.1</b> Aside: formal test of equality of variance</a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="one-way-anova-in-r.html"><a href="one-way-anova-in-r.html#interpreting-the-results"><i class="fa fa-check"></i><b>25.6</b> Interpreting the results</a></li>
<li class="chapter" data-level="25.7" data-path="one-way-anova-in-r.html"><a href="one-way-anova-in-r.html#summarise-results"><i class="fa fa-check"></i><b>25.7</b> Summarising and presenting the results of ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="multiple-comparison-tests.html"><a href="multiple-comparison-tests.html"><i class="fa fa-check"></i><b>26</b> Multiple comparison tests</a><ul>
<li class="chapter" data-level="26.1" data-path="multiple-comparison-tests.html"><a href="multiple-comparison-tests.html#introduction-7"><i class="fa fa-check"></i><b>26.1</b> Introduction</a></li>
<li class="chapter" data-level="26.2" data-path="multiple-comparison-tests.html"><a href="multiple-comparison-tests.html#mult-comp-R"><i class="fa fa-check"></i><b>26.2</b> Tukey’s HSD in R</a></li>
<li class="chapter" data-level="26.3" data-path="multiple-comparison-tests.html"><a href="multiple-comparison-tests.html#how-to-summarise-multiple-comparison-results"><i class="fa fa-check"></i><b>26.3</b> How to summarise multiple-comparison results</a></li>
<li class="chapter" data-level="26.4" data-path="multiple-comparison-tests.html"><a href="multiple-comparison-tests.html#doing-it-the-easy-way"><i class="fa fa-check"></i><b>26.4</b> Doing it the easy way…</a></li>
<li class="chapter" data-level="26.5" data-path="multiple-comparison-tests.html"><a href="multiple-comparison-tests.html#summarise"><i class="fa fa-check"></i><b>26.5</b> Summarising and presenting the results of a Tukey test</a></li>
<li class="chapter" data-level="26.6" data-path="multiple-comparison-tests.html"><a href="multiple-comparison-tests.html#significant-anova-but-no-differences-in-a-tukey-test"><i class="fa fa-check"></i><b>26.6</b> Significant ANOVA but no differences in a Tukey test?</a></li>
</ul></li>
<li class="part"><span><b>Experimental Design and ANOVA (II)</b></span></li>
<li class="chapter" data-level="27" data-path="introduction-to-two-way-anova.html"><a href="introduction-to-two-way-anova.html"><i class="fa fa-check"></i><b>27</b> Introduction to two-way ANOVA</a><ul>
<li class="chapter" data-level="27.1" data-path="parametric-statistics.html"><a href="parametric-statistics.html#introduction"><i class="fa fa-check"></i><b>27.1</b> Introduction</a></li>
<li class="chapter" data-level="27.2" data-path="introduction-to-two-way-anova.html"><a href="introduction-to-two-way-anova.html#degrees-of-freedom-mean-squares-and-f-statistics"><i class="fa fa-check"></i><b>27.2</b> Degrees of freedom, mean squares, and <em>F</em>-statistics</a></li>
<li class="chapter" data-level="27.3" data-path="introduction-to-two-way-anova.html"><a href="introduction-to-two-way-anova.html#multiple-comparison-tests-1"><i class="fa fa-check"></i><b>27.3</b> Multiple comparison tests</a></li>
<li class="chapter" data-level="27.4" data-path="introduction-to-two-way-anova.html"><a href="introduction-to-two-way-anova.html#beyond-two-way-anova"><i class="fa fa-check"></i><b>27.4</b> Beyond two-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html"><i class="fa fa-check"></i><b>28</b> Two-way ANOVA in R</a><ul>
<li class="chapter" data-level="28.1" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#introduction-8"><i class="fa fa-check"></i><b>28.1</b> Introduction</a></li>
<li class="chapter" data-level="28.2" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#competition-between-calluna-and-festuca"><i class="fa fa-check"></i><b>28.2</b> Competition between <em>Calluna</em> and <em>Festuca</em></a></li>
<li class="chapter" data-level="28.3" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#visualising-the-data-1"><i class="fa fa-check"></i><b>28.3</b> Visualising the data</a></li>
<li class="chapter" data-level="28.4" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#fitting-the-anova-model-and-interpreting-the-results"><i class="fa fa-check"></i><b>28.4</b> Fitting the ANOVA model and interpreting the results</a></li>
<li class="chapter" data-level="28.5" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#diagnostics-1"><i class="fa fa-check"></i><b>28.5</b> Diagnostics</a></li>
<li class="chapter" data-level="28.6" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#interpreting-the-results-1"><i class="fa fa-check"></i><b>28.6</b> Interpreting the results</a><ul>
<li class="chapter" data-level="28.6.1" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#understanding-the-model-graphically"><i class="fa fa-check"></i><b>28.6.1</b> Understanding the model graphically</a></li>
</ul></li>
<li class="chapter" data-level="28.7" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#multiple-comparison-tests-2"><i class="fa fa-check"></i><b>28.7</b> Multiple comparison tests</a></li>
<li class="chapter" data-level="28.8" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#drawing-conclusions-and-presenting-results"><i class="fa fa-check"></i><b>28.8</b> Drawing conclusions and presenting results</a><ul>
<li class="chapter" data-level="28.8.1" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#a-little-more-customisation"><i class="fa fa-check"></i><b>28.8.1</b> A little more customisation</a></li>
</ul></li>
<li class="chapter" data-level="28.9" data-path="two-way-anova-in-r.html"><a href="two-way-anova-in-r.html#balanced-or-orthogonal-designs"><i class="fa fa-check"></i><b>28.9</b> Balanced or orthogonal designs</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="anova-for-randomised-block-designs.html"><a href="anova-for-randomised-block-designs.html"><i class="fa fa-check"></i><b>29</b> ANOVA for randomised block designs</a><ul>
<li class="chapter" data-level="29.1" data-path="anova-for-randomised-block-designs.html"><a href="anova-for-randomised-block-designs.html#randomized-complete-block-designs"><i class="fa fa-check"></i><b>29.1</b> Randomized Complete Block Designs</a></li>
<li class="chapter" data-level="29.2" data-path="anova-for-randomised-block-designs.html"><a href="anova-for-randomised-block-designs.html#designs-without-replication"><i class="fa fa-check"></i><b>29.2</b> Designs without replication</a></li>
<li class="chapter" data-level="29.3" data-path="anova-for-randomised-block-designs.html"><a href="anova-for-randomised-block-designs.html#analysing-an-rcbd-experiment"><i class="fa fa-check"></i><b>29.3</b> Analysing an RCBD experiment</a></li>
<li class="chapter" data-level="29.4" data-path="anova-for-randomised-block-designs.html"><a href="anova-for-randomised-block-designs.html#carrying-out-the-analysis-with-r"><i class="fa fa-check"></i><b>29.4</b> Carrying out the analysis with R</a><ul>
<li class="chapter" data-level="29.4.1" data-path="anova-for-randomised-block-designs.html"><a href="anova-for-randomised-block-designs.html#multiple-comparisons-anyone"><i class="fa fa-check"></i><b>29.4.1</b> Multiple comparisons anyone?</a></li>
</ul></li>
<li class="chapter" data-level="29.5" data-path="anova-for-randomised-block-designs.html"><a href="anova-for-randomised-block-designs.html#are-there-disadvantages-to-randomised-block-designs"><i class="fa fa-check"></i><b>29.5</b> Are there disadvantages to randomised block designs?</a></li>
<li class="chapter" data-level="29.6" data-path="anova-for-randomised-block-designs.html"><a href="anova-for-randomised-block-designs.html#multiple-blocking-factors"><i class="fa fa-check"></i><b>29.6</b> Multiple blocking factors</a></li>
</ul></li>
<li class="part"><span><b>Fixing Problems</b></span></li>
<li class="chapter" data-level="30" data-path="data-transformations.html"><a href="data-transformations.html"><i class="fa fa-check"></i><b>30</b> Data transformations</a><ul>
<li class="chapter" data-level="30.1" data-path="data-transformations.html"><a href="data-transformations.html#transforms-introduction"><i class="fa fa-check"></i><b>30.1</b> Data that violate ANOVA assumptions</a></li>
<li class="chapter" data-level="30.2" data-path="data-transformations.html"><a href="data-transformations.html#ant-eg"><i class="fa fa-check"></i><b>30.2</b> Data transformation: ANOVAs and <em>t</em>-tests</a><ul>
<li class="chapter" data-level="30.2.1" data-path="data-transformations.html"><a href="data-transformations.html#the-data-foraging-in-ants"><i class="fa fa-check"></i><b>30.2.1</b> The data: foraging in ants</a></li>
<li class="chapter" data-level="30.2.2" data-path="data-transformations.html"><a href="data-transformations.html#fit-the-model-and-checking-the-assumptions"><i class="fa fa-check"></i><b>30.2.2</b> Fit the model and checking the assumptions</a></li>
</ul></li>
<li class="chapter" data-level="30.3" data-path="data-transformations.html"><a href="data-transformations.html#carry-on"><i class="fa fa-check"></i><b>30.3</b> Carrying on anyway</a></li>
<li class="chapter" data-level="30.4" data-path="data-transformations.html"><a href="data-transformations.html#transform"><i class="fa fa-check"></i><b>30.4</b> Transforming the data</a><ul>
<li class="chapter" data-level="30.4.1" data-path="data-transformations.html"><a href="data-transformations.html#the-logarithmic-transformation"><i class="fa fa-check"></i><b>30.4.1</b> The logarithmic transformation</a></li>
<li class="chapter" data-level="30.4.2" data-path="data-transformations.html"><a href="data-transformations.html#presenting-results-from-analyses-of-transformed-data"><i class="fa fa-check"></i><b>30.4.2</b> Presenting results from analyses of transformed data</a></li>
</ul></li>
<li class="chapter" data-level="30.5" data-path="data-transformations.html"><a href="data-transformations.html#trans-types"><i class="fa fa-check"></i><b>30.5</b> Types of transformations</a><ul>
<li class="chapter" data-level="30.5.1" data-path="data-transformations.html"><a href="data-transformations.html#logarithms"><i class="fa fa-check"></i><b>30.5.1</b> Logarithms</a></li>
<li class="chapter" data-level="30.5.2" data-path="data-transformations.html"><a href="data-transformations.html#square-roots"><i class="fa fa-check"></i><b>30.5.2</b> Square roots</a></li>
<li class="chapter" data-level="30.5.3" data-path="data-transformations.html"><a href="data-transformations.html#arcsine-square-root"><i class="fa fa-check"></i><b>30.5.3</b> Arcsine square root</a></li>
<li class="chapter" data-level="30.5.4" data-path="data-transformations.html"><a href="data-transformations.html#squaring"><i class="fa fa-check"></i><b>30.5.4</b> Squaring</a></li>
<li class="chapter" data-level="30.5.5" data-path="data-transformations.html"><a href="data-transformations.html#situations-which-cannot-be-dealt-with-by-transformations"><i class="fa fa-check"></i><b>30.5.5</b> Situations which cannot be dealt with by transformations</a></li>
</ul></li>
<li class="chapter" data-level="30.6" data-path="data-transformations.html"><a href="data-transformations.html#what-about-other-kinds-of-models"><i class="fa fa-check"></i><b>30.6</b> What about other kinds of models?</a></li>
<li class="chapter" data-level="30.7" data-path="data-transformations.html"><a href="data-transformations.html#final-thoughts"><i class="fa fa-check"></i><b>30.7</b> Final thoughts</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html"><i class="fa fa-check"></i><b>31</b> Non-parametric tests</a><ul>
<li class="chapter" data-level="31.1" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#what-is-non-par"><i class="fa fa-check"></i><b>31.1</b> What is a non-parametric test?</a></li>
<li class="chapter" data-level="31.2" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#non-par-intro"><i class="fa fa-check"></i><b>31.2</b> How does a non-parametric test work?</a></li>
<li class="chapter" data-level="31.3" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#non-parametric-equivalents-to-t-tests-and-anova"><i class="fa fa-check"></i><b>31.3</b> Non-parametric equivalents to <em>t</em>-tests and ANOVA</a></li>
<li class="chapter" data-level="31.4" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>31.4</b> Wilcoxon signed-rank test</a><ul>
<li class="chapter" data-level="31.4.1" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#leaf-damage-plant-defences-and-feeding-by-winter-moth-larvae"><i class="fa fa-check"></i><b>31.4.1</b> Leaf damage, plant defences and feeding by winter moth larvae</a></li>
</ul></li>
<li class="chapter" data-level="31.5" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#mann-whitney"><i class="fa fa-check"></i><b>31.5</b> The Mann-Whitney <em>U</em>-test</a><ul>
<li class="chapter" data-level="31.5.1" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#ant-foraging"><i class="fa fa-check"></i><b>31.5.1</b> Ant foraging</a></li>
</ul></li>
<li class="chapter" data-level="31.6" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#the-kruskal-wallis-test"><i class="fa fa-check"></i><b>31.6</b> The Kruskal-Wallis test</a><ul>
<li class="chapter" data-level="31.6.1" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#learning-in-cuttlefish"><i class="fa fa-check"></i><b>31.6.1</b> Learning in cuttlefish</a></li>
</ul></li>
<li class="chapter" data-level="31.7" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#why-when"><i class="fa fa-check"></i><b>31.7</b> Why use non-parametric tests … and when?</a><ul>
<li class="chapter" data-level="31.7.1" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#what-are-the-advantages"><i class="fa fa-check"></i><b>31.7.1</b> What are the advantages?</a></li>
<li class="chapter" data-level="31.7.2" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#what-are-the-disadvantages"><i class="fa fa-check"></i><b>31.7.2</b> What are the disadvantages?</a></li>
<li class="chapter" data-level="31.7.3" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html#parting-words"><i class="fa fa-check"></i><b>31.7.3</b> Parting words</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Supplementary Material</b></span></li>
<li class="chapter" data-level="A" data-path="exercises.html"><a href="exercises.html"><i class="fa fa-check"></i><b>A</b> Exercises</a><ul>
<li class="chapter" data-level="A.1" data-path="exercises.html"><a href="exercises.html#week-2"><i class="fa fa-check"></i><b>A.1</b> Week 2</a><ul>
<li class="chapter" data-level="A.1.1" data-path="exercises.html"><a href="exercises.html#what-kind-of-variable-is-it"><i class="fa fa-check"></i><b>A.1.1</b> What kind of variable is it?</a></li>
<li class="chapter" data-level="A.1.2" data-path="exercises.html"><a href="exercises.html#definitions"><i class="fa fa-check"></i><b>A.1.2</b> Definitions</a></li>
<li class="chapter" data-level="A.1.3" data-path="exercises.html"><a href="exercises.html#what-form-do-sampling-distributions-take"><i class="fa fa-check"></i><b>A.1.3</b> What form do sampling distributions take?</a></li>
<li class="chapter" data-level="A.1.4" data-path="exercises.html"><a href="exercises.html#how-does-sample-size-influence-the-standard-error"><i class="fa fa-check"></i><b>A.1.4</b> How does sample size influence the standard error?</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="exercises.html"><a href="exercises.html#week-3"><i class="fa fa-check"></i><b>A.2</b> Week 3</a><ul>
<li class="chapter" data-level="A.2.1" data-path="exercises.html"><a href="exercises.html#sample-size-and-statistical-power"><i class="fa fa-check"></i><b>A.2.1</b> Sample size and statistical power</a></li>
<li class="chapter" data-level="A.2.2" data-path="exercises.html"><a href="exercises.html#a-bit-more-about-statistical-power"><i class="fa fa-check"></i><b>A.2.2</b> A bit more about statistical power</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="exercises.html"><a href="exercises.html#week-4"><i class="fa fa-check"></i><b>A.3</b> Week 4</a><ul>
<li class="chapter" data-level="A.3.1" data-path="exercises.html"><a href="exercises.html#eagle-owls-and-norway-rats"><i class="fa fa-check"></i><b>A.3.1</b> Eagle owls and Norway rats</a></li>
<li class="chapter" data-level="A.3.2" data-path="exercises.html"><a href="exercises.html#the-power-of-pairing"><i class="fa fa-check"></i><b>A.3.2</b> The power of pairing</a></li>
<li class="chapter" data-level="A.3.3" data-path="exercises.html"><a href="exercises.html#fungal-infection-in-french-beans"><i class="fa fa-check"></i><b>A.3.3</b> Fungal infection in French beans</a></li>
<li class="chapter" data-level="A.3.4" data-path="exercises.html"><a href="exercises.html#sheep-grass"><i class="fa fa-check"></i><b>A.3.4</b> Sheep, grass and nature reserves</a></li>
</ul></li>
<li class="chapter" data-level="A.4" data-path="exercises.html"><a href="exercises.html#week-5"><i class="fa fa-check"></i><b>A.4</b> Week 5</a><ul>
<li class="chapter" data-level="A.4.1" data-path="exercises.html"><a href="exercises.html#oviposition-behaviour-in-bean-weevils"><i class="fa fa-check"></i><b>A.4.1</b> Oviposition behaviour in bean weevils</a></li>
<li class="chapter" data-level="A.4.2" data-path="exercises.html"><a href="exercises.html#determining-expected-values"><i class="fa fa-check"></i><b>A.4.2</b> Determining expected values</a></li>
<li class="chapter" data-level="A.4.3" data-path="exercises.html"><a href="exercises.html#sex-and-eye-colour"><i class="fa fa-check"></i><b>A.4.3</b> Sex and eye colour</a></li>
<li class="chapter" data-level="A.4.4" data-path="exercises.html"><a href="exercises.html#eagle-owls-and-prey-choice"><i class="fa fa-check"></i><b>A.4.4</b> Eagle owls and prey choice</a></li>
</ul></li>
<li class="chapter" data-level="A.5" data-path="exercises.html"><a href="exercises.html#week-6"><i class="fa fa-check"></i><b>A.5</b> Week 6</a><ul>
<li class="chapter" data-level="A.5.1" data-path="exercises.html"><a href="exercises.html#hedgerows-and-partridges"><i class="fa fa-check"></i><b>A.5.1</b> Hedgerows and partridges</a></li>
<li class="chapter" data-level="A.5.2" data-path="exercises.html"><a href="exercises.html#analysing-associations"><i class="fa fa-check"></i><b>A.5.2</b> Analysing associations</a></li>
<li class="chapter" data-level="A.5.3" data-path="exercises.html"><a href="exercises.html#diagnosing-problems"><i class="fa fa-check"></i><b>A.5.3</b> Diagnosing problems</a></li>
</ul></li>
<li class="chapter" data-level="A.6" data-path="exercises.html"><a href="exercises.html#week-7"><i class="fa fa-check"></i><b>A.6</b> Week 7</a><ul>
<li class="chapter" data-level="A.6.1" data-path="exercises.html"><a href="exercises.html#lead-pollution-in-lakes"><i class="fa fa-check"></i><b>A.6.1</b> Lead pollution in lakes</a></li>
<li class="chapter" data-level="A.6.2" data-path="exercises.html"><a href="exercises.html#the-effect-of-molluscicide-on-rates-of-movement-in-slugs"><i class="fa fa-check"></i><b>A.6.2</b> The effect of molluscicide on rates of movement in slugs</a></li>
<li class="chapter" data-level="A.6.3" data-path="exercises.html"><a href="exercises.html#multiple-comparisons-slug-movement-and-molluscicide"><i class="fa fa-check"></i><b>A.6.3</b> Multiple comparisons — slug movement and molluscicide</a></li>
</ul></li>
<li class="chapter" data-level="A.7" data-path="exercises.html"><a href="exercises.html#week-8"><i class="fa fa-check"></i><b>A.7</b> Week 8</a><ul>
<li class="chapter" data-level="A.7.1" data-path="exercises.html"><a href="exercises.html#limpets-and-salinity"><i class="fa fa-check"></i><b>A.7.1</b> Limpets and salinity</a></li>
<li class="chapter" data-level="A.7.2" data-path="exercises.html"><a href="exercises.html#sheep-grass-and-nature-reserves-again"><i class="fa fa-check"></i><b>A.7.2</b> Sheep, grass and nature reserves (again)</a></li>
</ul></li>
<li class="chapter" data-level="A.8" data-path="exercises.html"><a href="exercises.html#week-9"><i class="fa fa-check"></i><b>A.8</b> Week 9</a><ul>
<li class="chapter" data-level="A.8.1" data-path="exercises.html"><a href="exercises.html#fungal-pathogen-infection-on-leaves"><i class="fa fa-check"></i><b>A.8.1</b> Fungal pathogen infection on leaves</a></li>
<li class="chapter" data-level="A.8.2" data-path="exercises.html"><a href="exercises.html#pollution-sensitive-stoneflies---whats-going-into-the-river"><i class="fa fa-check"></i><b>A.8.2</b> Pollution sensitive stoneflies - what’s going into the river?</a></li>
<li class="chapter" data-level="A.8.3" data-path="exercises.html"><a href="exercises.html#ants-again"><i class="fa fa-check"></i><b>A.8.3</b> Ants again</a></li>
<li class="chapter" data-level="A.8.4" data-path="exercises.html"><a href="exercises.html#bryophyte-diversity-in-a-woodland"><i class="fa fa-check"></i><b>A.8.4</b> Bryophyte diversity in a woodland</a></li>
<li class="chapter" data-level="A.8.5" data-path="exercises.html"><a href="exercises.html#reporting-the-results-of-non-parametric-tests"><i class="fa fa-check"></i><b>A.8.5</b> Reporting the results of non-parametric tests</a></li>
<li class="chapter" data-level="A.8.6" data-path="exercises.html"><a href="exercises.html#copper-tolerance-in-agrostis"><i class="fa fa-check"></i><b>A.8.6</b> Copper tolerance in <em>Agrostis</em></a></li>
<li class="chapter" data-level="A.8.7" data-path="exercises.html"><a href="exercises.html#measuring-seed-dispersal"><i class="fa fa-check"></i><b>A.8.7</b> Measuring seed dispersal</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html"><i class="fa fa-check"></i><b>B</b> Choosing models and tests</a><ul>
<li class="chapter" data-level="B.1" data-path="introduction-to-one-way-anova.html"><a href="introduction-to-one-way-anova.html#intro"><i class="fa fa-check"></i><b>B.1</b> Introduction</a><ul>
<li class="chapter" data-level="B.1.1" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#do-we-need-to-carry-out-a-statistical-analysis"><i class="fa fa-check"></i><b>B.1.1</b> Do we need to carry out a statistical analysis?</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#getting-started"><i class="fa fa-check"></i><b>B.2</b> Getting started…</a></li>
<li class="chapter" data-level="B.3" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#a-key-to-choosing-statistical-models-and-tests"><i class="fa fa-check"></i><b>B.3</b> A key to choosing statistical models and tests</a></li>
<li class="chapter" data-level="B.4" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#four-questions"><i class="fa fa-check"></i><b>B.4</b> Four main types of question</a></li>
<li class="chapter" data-level="B.5" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#qu1"><i class="fa fa-check"></i><b>B.5</b> Question 1 –- Comparison of group means or medians</a><ul>
<li class="chapter" data-level="B.5.1" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#question-1-how-many-groups"><i class="fa fa-check"></i><b>B.5.1</b> Question 1 How many groups?</a></li>
<li class="chapter" data-level="B.5.2" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#question-1-single-group"><i class="fa fa-check"></i><b>B.5.2</b> [Question 1] Single group</a></li>
<li class="chapter" data-level="B.5.3" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#question-1-two-groups"><i class="fa fa-check"></i><b>B.5.3</b> [Question 1] Two groups</a></li>
<li class="chapter" data-level="B.5.4" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#question-1-more-than-two-groups"><i class="fa fa-check"></i><b>B.5.4</b> [Question 1] More than two groups</a></li>
</ul></li>
<li class="chapter" data-level="B.6" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#qu2"><i class="fa fa-check"></i><b>B.6</b> Question 2 – Associations between two variables?</a><ul>
<li class="chapter" data-level="B.6.1" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#question-2-testing-y-as-a-function-of-x-or-an-association-between-x-and-y"><i class="fa fa-check"></i><b>B.6.1</b> [Question 2] Testing <span class="math inline">\(y\)</span> as a function of <span class="math inline">\(x\)</span>, or an association between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>?</a></li>
</ul></li>
<li class="chapter" data-level="B.7" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#qu4"><i class="fa fa-check"></i><b>B.7</b> Question 3 -– Frequencies of categorical data</a></li>
<li class="chapter" data-level="B.8" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#var-cat"><i class="fa fa-check"></i><b>B.8</b> Variables or categories?</a><ul>
<li class="chapter" data-level="B.8.1" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#anova-vs.regression"><i class="fa fa-check"></i><b>B.8.1</b> ANOVA vs. regression</a></li>
<li class="chapter" data-level="B.8.2" data-path="choosing-models-and-tests.html"><a href="choosing-models-and-tests.html#making-categories-out-of-continuous-measures"><i class="fa fa-check"></i><b>B.8.2</b> Making categories out of continuous measures</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="C" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html"><i class="fa fa-check"></i><b>C</b> Writing a scientific report</a><ul>
<li class="chapter" data-level="C.1" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#introduction-9"><i class="fa fa-check"></i><b>C.1</b> Introduction</a></li>
<li class="chapter" data-level="C.2" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#the-structure-of-a-scientific-report"><i class="fa fa-check"></i><b>C.2</b> The structure of a scientific report</a><ul>
<li class="chapter" data-level="C.2.1" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#title"><i class="fa fa-check"></i><b>C.2.1</b> Title</a></li>
<li class="chapter" data-level="C.2.2" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#abstract-or-summary"><i class="fa fa-check"></i><b>C.2.2</b> Abstract or Summary</a></li>
<li class="chapter" data-level="C.2.3" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#introduction-10"><i class="fa fa-check"></i><b>C.2.3</b> Introduction</a></li>
<li class="chapter" data-level="C.2.4" data-path="index.html"><a href="index.html#methods"><i class="fa fa-check"></i><b>C.2.4</b> Methods</a></li>
<li class="chapter" data-level="C.2.5" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#results"><i class="fa fa-check"></i><b>C.2.5</b> Results</a></li>
<li class="chapter" data-level="C.2.6" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#discussion"><i class="fa fa-check"></i><b>C.2.6</b> Discussion</a></li>
<li class="chapter" data-level="C.2.7" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#acknowledgements"><i class="fa fa-check"></i><b>C.2.7</b> Acknowledgements</a></li>
<li class="chapter" data-level="C.2.8" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#literature-cited-references"><i class="fa fa-check"></i><b>C.2.8</b> Literature cited / References</a></li>
<li class="chapter" data-level="C.2.9" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#appendices"><i class="fa fa-check"></i><b>C.2.9</b> Appendices</a></li>
</ul></li>
<li class="chapter" data-level="C.3" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#presenting-species-names"><i class="fa fa-check"></i><b>C.3</b> Presenting species names</a></li>
<li class="chapter" data-level="C.4" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#approaches-to-writing"><i class="fa fa-check"></i><b>C.4</b>  Approaches to writing</a><ul>
<li class="chapter" data-level="C.4.1" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#a-last-piece-of-advice"><i class="fa fa-check"></i><b>C.4.1</b> A last piece of advice…</a></li>
</ul></li>
<li class="chapter" data-level="C.5" data-path="writing-a-scientific-report.html"><a href="writing-a-scientific-report.html#further-reading-1"><i class="fa fa-check"></i><b>C.5</b> Further reading</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">APS 240: Data Analysis and Statistics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="paired-sample-t-tests" class="section level1">
<h1><span class="header-section-number">Chapter 14</span> Paired-sample <em>t</em>-tests</h1>
<div id="when-do-we-use-a-paired-sample-t-test" class="section level2">
<h2><span class="header-section-number">14.1</span> When do we use a paired-sample <em>t</em>-test?</h2>
<p>In the previous chapter we learned how to use a two-sample <em>t</em>-test to compare means among two populations. This test is sometimes called an independent two-sample <em>t</em>-test because the two samples are entirely independent sets of measurements (e.g. purple plant dry weights vs. green plant dry weights). A measurement in one sample has no link to any particular measurement in the second sample. That’s what ‘independent’ means in the context of a two sample <em>t</em>-test. However, there are situations in which data may naturally form pairs of non-independent observations: the first value in a sample A is linked in some way to the first value in sample B, the second value in sample A is linked with the second value in sample B, and so on. This is known, unsurprisingly, as a <em>paired-sample</em> design. Here are a couple of examples…</p>
<ul>
<li><p>A common example of a paired-sample design is the situation where we have a set of organisms, and we record some measurement from each organism before and after an experimental treatment. For example, if we were studying heart rate in relation to position (sitting vs. standing) we might measure the heart rate of a number of people in both positions. In this case the heart rate of a particular person when sitting is paired with the heart rate of the same person when standing.</p></li>
<li><p>One of the consequences of habitat fragmentation is that it increases the relative amount of ‘edge’ habitat. If we are studying habitat fragmentation in forests we may want to know if biodiversity is different at the edges of forest fragments, compared to their centres. We could measure the biodiversity of different forest fragments in two places: at their edges and at their centres. In this case, edges and centres are obviously paired.</p></li>
</ul>
<p>We should not use a two-sample <em>t</em>-test when our data have this kind of structure. Why? In biology, we often have the problem that there is a great deal of variation between the items we’re studying (individual organisms, forest sites, etc). In some cases, there may be so much among-item variation that the effect of any difference among the situations we’re really interested in is obscured. A paired-sample design is a very useful way to control for this variation. Let’s see why…</p>
</div>
<div id="why-do-we-use-a-paired-sample-design" class="section level2">
<h2><span class="header-section-number">14.2</span> Why do we use a paired-sample design?</h2>
<p>Consider the following. A drug company wishes to test two drugs for their effectiveness in treating a rare illness in which glycolipids are poorly metabolised. An effective drug is one that lowers glycolipid concentrations in patients. The company is only able to find 8 patients willing to cooperate in the early trials of the two drugs (they might be dangerous!). What’s more, the 8 patients vary in their age, sex, body weight, severity of symptoms and other health problems.</p>
<p>If the 8 patients were randomly assigned to one or other drug treatments and their performance monitored, it would be likely be very difficult to detect statistically significant differences between the treatments. This is because we have an experiment which provides very little replication, yet we expect considerable variability from one person to another in the levels of glycolipid before any treatment is applied. We expect this variability to lead to a large standard error in the difference between means.</p>
<p>One solution to this problems is to treat each patient <em>with both drugs in turn</em> and record the glycolipid concentrations in the blood, for each patient, after a period taking each drug. One arrangement would be for four patients to start with drug A and four with drug B, and then after a suitable break from the treatments, they could be swapped over onto the other drug. This would give us eight replicate observations on the effectiveness of each drug and we can determine for each patient which drug is more effective.<a href="#fn13" class="footnoteRef" id="fnref13"><sup>13</sup></a></p>
<p>The experimental design, and one hypothetical outcome, is represented in the diagram below…</p>
<div class="figure" style="text-align: center"><span id="fig:drug-linked"></span>
<img src="stats-for-bio_files/figure-html/drug-linked-1.png" alt="Data from glycolipid study, showing paired design. Each patient is denoted by a unique number." width="50%" />
<p class="caption">
Figure 14.1: Data from glycolipid study, showing paired design. Each patient is denoted by a unique number.
</p>
</div>
<p>Each patient is represented by a unique number (1-9) (the order of the drugs in the plot does not matter—it doesn’t mean that Drug A was tested before Drug B just because Drug A appears first). Notice that there is a lot of variability in these data, both in the glycolipid levels of each patient, and also in the amount by which the drugs differ in their effects (e.g. the drugs have roughly equal effects for patient 5, while drug B appears to be more effective for patient 2). What is obvious from this pattern is that although the glycolipid levels vary a good deal between patients, Drug B seems to reduce glycolipid levels more than Drug A.</p>
<p>The advantage to using a paired-sample design in this case is clear if we look at the results we might have obtained on the same patients but by dividing them into two groups of four and giving one group Drug A and one group Drug B:</p>
<div class="figure" style="text-align: center"><span id="fig:drug-not-linked"></span>
<img src="stats-for-bio_files/figure-html/drug-not-linked-1.png" alt="Data from glycolipid study, ignoring paired design." width="50%" />
<p class="caption">
Figure 14.2: Data from glycolipid study, ignoring paired design.
</p>
</div>
<p>The patients and their glycolipid levels are identical to those in the previous diagram, but only patients 2, 3, 4 and 8 (selected at random) were given Drug A, while only patients 1, 5, 6, and 7 were given Drug B. If you calculated the means of the two groups, they would be different, with Drug B performing better, but the associated standard error would also be large relative to this difference. A two-sample <em>t</em>-test would certainly fail to identify a significant difference between the two drugs.</p>
<p>So, it would be quite possible to end up with two groups where there was no clear difference in the mean glycolipid levels between the two drug treatments even though (as we have seen in the previous diagram) Drug B seems to be more effective in the majority of patients. What the pairing is doing is allowing us to factor out (i.e. remove) the variation among individuals, and concentrate on the differences between the two treatments. The result is a much more sensitive evaluation of the effect we’re interested in.</p>
<p>The next question is, how do we go about analysing paired data in a way that properly accounts for the structure in the data?</p>
</div>
<div id="how-do-you-carry-out-a-t-test-on-paired-samples" class="section level2">
<h2><span class="header-section-number">14.3</span> How do you carry out a <em>t</em>-test on paired-samples?</h2>
<p>It should be clear why a paired-sample design might be useful, but how do we actually construct the right test? The ‘trick’ is to work directly with the differences between pairs of values. So in the case of the glycolipid levels illustrated in the first diagram, we noted that there was a greater decrease of glycolipids in 75% of patients using Drug B compared with Drug A.</p>
<p>If we calculate the actual differences (i.e. subtracted the value for Drug A from the value for Drug B) for each patient we might see something like…</p>
<pre><code>## -3.9 -4.3 2.5 -4.5 0.5 -3.9 -7.1 -2.6</code></pre>
<p>Notice that there are only two positive values in this sample of differences, one of which is fairly close to 0. The mean difference is -2.9, i.e. on average, glycolipid levels are lower with Drug B. Another way of stating this observation is that <em>within subjects</em> (patients), the mean difference between drug B and drug A is negative. A paired-sample design focusses on the within-subject (or more generally, within-item) change.</p>
<p>If, on the other hand, the two drugs had had similar effects then what would we expect to see? We would expect no consistent difference in glycolipid levels between the Drug A and Drug B treatments. Glycolipid levels are unlikely to remain exactly the same over time, but there shouldn’t be any pattern to these changes with respect to the drug treatment, some patients will show increases, some decreases, and some no change at all. The mean of the differences in this case should be somewhere around zero (although sampling variation will ensure it isn’t exactly equal to zero).</p>
<p>So, what we do to carry out a <em>t</em>-test on paired-sample data is to find the mean of the difference of all the pairs and test this to see if it is significantly different from zero. You already know how to do this! <strong>This is just an application of the one-sample <em>t</em>-test</strong>, where the expected value (i.e. the null hypothesis) is 0. The thing to remember here is that although we started out with two sets of values, the sample we are actually evaluating are the differences between pairs. The population we’re interested in a ‘population of differences’.</p>
<p>When used to analyse paired data in this way, the test is referred to as a paired-sample <em>t</em>-test. This is not wrong, but it important to remember that a paired-sample <em>t</em>-test is is really it is just a one-sample <em>t</em>-test applied to the sample of differences between pairs of associated observations. A paired-sample <em>t</em>-test isn’t really a new kind of test. Instead, it is a one-sample <em>t</em>-test applied to <em>a new kind of situation</em>. R offers the option of a paired-sample <em>t</em>-test to save us the effort of calculating differences. It calculates the differences between pairs for us as part of the test, although ultimately, it just carries out a one-sample test on those differences. We can easily calculate differences ourselves and then carry out a one-sample <em>t</em>-test with the new sample. We’ll look at how to do it the ‘old fashioned’ way first—calculating the differences and running a one-sample test—before using the short-cut method provided by R.</p>
<p>Let’s briefly review the assumptions of the test first. This won’t take long…</p>
<div id="assumptions-of-the-one-sample-t-test-1" class="section level3">
<h3><span class="header-section-number">14.3.1</span> Assumptions of the one-sample <em>t</em>-test</h3>
<p>The assumptions of a paired-sample <em>t</em>-test are no different from the one-sample <em>t</em>-test—ultimately they boil down to the same test! We just have to be aware of the target sample. The key point to keep in mind is that it is the sample of differences that is important, not the original data. There is no requirement for the original data to be drawn from a normal distribution because the normality assumption applies to the differences. This is very useful, because even where the original data seem to be drawn from a non-normal distribution, the differences between pairs can often be acceptably normal. The differences do need to be measured on an interval or ratio scale, but this is guaranteed if the original data are on one of these scales.</p>
</div>
</div>
<div id="carrying-out-a-paired-sample-t-test-in-r" class="section level2">
<h2><span class="header-section-number">14.4</span> Carrying out a paired-sample <em>t</em>-test in R</h2>
<div class="do-something">
<p>
You should work through the example in this section.
</p>
</div>
<p>Staying with the problem of trials of two drugs for controlling glycolipid levels, the serum glycolipid concentration data from the trial illustrated above are stored in the GLYCOLIPID.CSV file. Download the this file from MOLE and place it in your working directory. Read GLYCOLIPID.CSV into an R data frame, giving it the name <code>glycolipid</code>.</p>
<p>As always, we should start by looking at the raw data. We’ll use <code>glimpse</code> to do this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(glycolipid)</code></pre></div>
<pre><code>## Observations: 16
## Variables: 4
## $ Patient    &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8
## $ Sex        &lt;fctr&gt; Male, Female, Male, Female, Female, Male, Female, ...
## $ Drug       &lt;fctr&gt; A, A, A, A, A, A, A, A, B, B, B, B, B, B, B, B
## $ Glycolipid &lt;dbl&gt; 142.9, 140.6, 144.7, 144.0, 142.4, 146.0, 149.1, 15...</code></pre>
<p>There are four variables in this data set: <code>Patient</code> indexes the patient identity, <code>Sex</code> is the sex of the patient (we don’t need this), <code>Drug</code> denotes the drug treatment, and <code>Glycolipid</code> is the glycolipid level.</p>
<p>Next, we need to calculate the differences between each pair. We can do this with the <code>dplyr</code> functions <code>group_by</code> and <code>summarise</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">glycolipid_diffs &lt;-<span class="st"> </span>
<span class="st">  </span>glycolipid %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Patient) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Difference =</span> <span class="kw">diff</span>(Glycolipid))</code></pre></div>
<p>That might look a little cryptic. What we did was group the data by the values of <code>Patient</code>, and then used a function called <code>diff</code> to calculate the difference between the two Glycolipid concentrations <em>within each patient</em>. We stored the result of this calculation in a new data frame called <code>glycolipid_diffs</code>. This is the data we’ll use to carry out the paired-sample <em>t</em>-test:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">glycolipid_diffs</code></pre></div>
<pre><code>## # A tibble: 8 × 2
##   Patient Difference
##     &lt;int&gt;      &lt;dbl&gt;
## 1       1       -3.8
## 2       2       -4.2
## 3       3        2.6
## 4       4       -4.6
## 5       5        0.6
## 6       6       -3.8
## 7       7       -7.0
## 8       8       -2.5</code></pre>
<p>We should try to check that the differences could plausibly have been drawn from a normal distribution, but to be honest, normality is quite hard to assess with only 8 observations:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(glycolipid_diffs, <span class="kw">aes</span>(<span class="dt">x =</span> Difference)) +
<span class="st">  </span><span class="kw">geom_dotplot</span>() +<span class="st"> </span><span class="kw">theme_grey</span>(<span class="dt">base_size =</span> <span class="dv">22</span>)</code></pre></div>
<pre><code>## `stat_bindot()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<div class="figure" style="text-align: center"><span id="fig:glyco-diffs"></span>
<img src="stats-for-bio_files/figure-html/glyco-diffs-1.png" alt="Within-individual differences from glycolipid study" width="50%" />
<p class="caption">
Figure 14.3: Within-individual differences from glycolipid study
</p>
</div>
<p>That’s an uninspiring figure, but the data seem OK, so let’s carry out a one-sample <em>t</em>-test on the calculated differences (remember, the null hypothesis is one where the population mean is zero). This is test is easy to do in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(glycolipid_diffs$Difference)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  glycolipid_diffs$Difference
## t = -2.6209, df = 7, p-value = 0.03436
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -5.397549 -0.277451
## sample estimates:
## mean of x 
##   -2.8375</code></pre>
<p>We don’t have to set the <code>data</code> argument to carry out a one-sample <em>t</em>-test on the differences. We just passed along one argument: numeric vector of differences extracted from <code>glycolipid_diffs</code> using the <code>$</code> operator. What happened to the <code>mu</code> argument used to set up the null hypothesis? R assumes that this is 0 if we don’t supply it, so no need to set it here.</p>
<p>The output has much the same structure as with two-sample <em>t</em>-tests…</p>
<p>The first line reminds us what kind of test we did, and the second line reminds us what data we used to carry out the test. It is the third line that matters: <code>t = -2.6209, df = 7, *p*-value = 0.03436</code>. This gives the <em>t</em>-statistic, the degrees of freedom, and the all-important <em>p</em>-value associated with the test. The <em>p</em>-value is tell us that the mean within-individual difference is significant at the <em>p</em> &lt; 0.05 level. The next line (<code>alternative hypothesis: true mean is not equal to 0</code>) reminds us that R has tested whether the population mean is equal to a value of zero, versus the alternative possibility that it is not equal to (i.e. greater or less than) zero.</p>
<p>We now need to express these results in a clear sentence incorporating the relevant statistical information to indicate whether we accept or reject our test hypothesis:</p>
<blockquote>
<p>Individual patients had significantly lower serum glycolipid concentrations when treated with Drug B than when treated with Drug A (<em>t</em> = 2.62, d.f. = 7, <em>p</em> = 0.034).</p>
</blockquote>
<p>Notice tha twe chose to report the actual <em>p</em>-value here because it is close to the <em>p</em> &lt; 0.05 significance level. There’s nothing wrong with writing ‘<em>p</em> &lt; 0.05’ instead, but ‘<em>p</em> = 0.034’ gives the reader a bit more information. There are a couple of things to point out in interpreting the result of such a test.</p>
<ol style="list-style-type: decimal">
<li><p>The sample of differences was used in the test, not the sample of paired observations. This means the degrees of freedom for a paired-sample <em>t</em> test are one less than the number of differences (the number of pairs); not one, or two, less than the total number of values.</p></li>
<li><p>Note that since we have used a paired-sample design our conclusion stresses the fact that the use of the Drug B results in a lower glycolipid level in individual patients; it doesn’t say that the use of Drug B resulted in lower glycolipid concentrations for everyone given Drug B than for anyone given Drug A.</p></li>
</ol>
<div id="using-the-paired-true-argument" class="section level3">
<h3><span class="header-section-number">14.4.1</span> Using the <code>paired = TRUE</code> argument</h3>
<p>As mentioned, R does have a built in procedure for doing paired-sample <em>t</em>-tests. Now that we’ve done it the hard way, let’s try carrying out the test using that procedure. This looks very similar to a two-sample <em>t</em>-test, except that now we have to set the <code>paired</code> argument of the <code>t.test</code> function to <code>TRUE</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(Glycolipid ~<span class="st"> </span>Drug, <span class="dt">data =</span> glycolipid, <span class="dt">paired =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Glycolipid by Drug
## t = 2.6209, df = 7, p-value = 0.03436
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.277451 5.397549
## sample estimates:
## mean of the differences 
##                  2.8375</code></pre>
<p>Notice that we work with the original <code>glycolipid</code> data frame rather than the <code>glycolipid_diffs</code> data frame we constructed above. R takes care of the differencing for us.</p>
<div class="do-something">
<p>
<strong>Order matters</strong>
</p>
<p>
Be careful when using the built in procedure for doing paired-sample <em>t</em>-tests. The only information R uses to associate pairs of observations is their order in each group. The first observation in the ‘A’ group is paired with the first observation in the ‘B’ group, the second observation in the ‘A’ group is paired with the second observation in the ‘B’ group, and so on. If the items/individuals aren’t ordered the same way in each group, you’ll end up with a meaningless <em>p</em>-value…
</p>
</div>
<p>R makes it easy to do paired-sample <em>t</em>-test. It is up to you which method you use for doing paired-sample <em>t</em>-tests, just don’t forget it is really only a one-sample test wearing fancy clothes.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="13">
<li id="fn13"><p>This kind of experimental design is called a cross-over study. It can be problematic if, for example, “carry-over” effects occur, e.g., the effect of one drug is altered when the other drug has previously been administered. We won’t worry about these problems here though.<a href="paired-sample-t-tests.html#fnref13">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="two-sample-t-test.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="one-tailed-vs-two-tailed-tests.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dzchilds/stats-for-bio/edit/master/3_03_t-tests_paired_sample.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
